plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-berry.js

changesetBaseRefs:
  - "main"
  - "origin/main"
  - "upstream/main"
